### ISSUE TITLE
Windows, zip corrupted 1.62

### ISSUE THREAD

**Issue by AsafMah** [dom96/choosenim#291] opened 2021-12-21 21:07 UTC
I can't install nim, this is the output:

```pwsh
.\choosenim-0.8.2_windows_amd64.exe 1.6.2 --verbose
      Info: No client ID found in 'C:\Users\x\.choosenim\analytics', not sending analytics.
      Info: No client ID found in 'C:\Users\x\.choosenim\analytics', not sending analytics.
      Info: C:\Users\x\.choosenim\downloads\dlls.zip already downloaded
 Extracting dlls.zip
Downloading Nim 1.6.2 from nim-lang.org
[##################################################] 100.0% 0kb/s
      Info: No client ID found in 'C:\Users\x\.choosenim\analytics', not sending analytics.
 Extracting nim-1.6.2_x8.zip
      Info: No client ID found in 'C:\Users\x\.choosenim\analytics', not sending analytics.
      Info: No client ID found in 'C:\Users\x\.choosenim\analytics', not sending analytics.
     Error: Unable to extract. Error was 'Attempted to read past end of file, corrupted zip archive?'.
```
Why is the file it downloads `nim-1.6.2_x8.zip`? shouldn't it be `nim-1.6.2_x64.zip`?

**Comment by dom96** [comment] 2021-12-21 21:45
Duplicate of https://github.com/dom96/choosenim/issues/249. Would appreciate your help in fixing that one :)

**Closed by dom96** 2021-12-21 21:45 UTC
