### ISSUE TITLE
Provided Windows executables are not working

### ISSUE THREAD

**Issue by bobeff** [dom96/choosenim#133] opened 2019-08-13 16:17 UTC
I tried to install `choosenim` for Windows by downloading the latest version [0.4.0](https://github.com/dom96/choosenim/releases/tag/v0.4.0) as well the previous version [0.3.2](https://github.com/dom96/choosenim/releases/tag/v0.3.2). I tried both the *self-extracting archives* and the *zip archives*, but the result is the same. On executing `runme.bat` file, the following error has occur:

> λ runme.bat
choosenim.nim(201)       choosenim
cliparams.nim(134)       newCliParams
config.nim(72)           parseConfig
Error: unhandled exception: Package list '' requires either url or path [NimbleError]
choosenim.nim(201)       choosenim
cliparams.nim(134)       newCliParams
config.nim(72)           parseConfig
Error: unhandled exception: Package list '' requires either url or path [NimbleError]
        1 file(s) copied.
            Work finished.
            Now you must ensure that the Nimble bin dir is in your PATH:
              C:\nimble\bin\
Press any key to continue . . .

Despite that the file `choosenim.exe` has appeared in the destination directory `c:\nimble\bin\` when I tried to use it, it has given me the following error for basically every command:
> choosenim.nim(201)       choosenim
cliparams.nim(134)       newCliParams
config.nim(72)           parseConfig
Error: unhandled exception: Package list '' requires either url or path [NimbleError]

I built it manually with the previously manually installed `nim` version and it works. But being not possible to work with directly downloaded from GitHub version is preventing me from using it for implementing Windows build target for Travis CI which is supported from some time.

My version of Windows is: `10.0.18362.0` for x64.

I suspect that this can have something in common with some incompatibility between `i386` build and `x64`  OS, because i observed that provided files contain `i386` in their names, but my windows is `x64` and as I already mentioned, manual build from source on my machine is working perfectly.

I built it with the following command: `nim c -d:danger --debugInfo --lineDir:on -o:%NIMBLEBIN%\choosenim.exe src/choosenim.nim` from the master branch, but it works also with the last two tagged commits in contrast with the downloaded binaries.

**Comment by dom96** [comment] 2019-08-13 18:22
choosenim read's nimble's config. It seems like you've got stuff in there that's not supported by this version of choosenim.

**Comment by dom96** [comment] 2019-08-13 18:23
and yeah, we need to make it so that choosenim doesn't crash in this case. Should be an easy PR (AFAIK there is an issue for this already as well).

**Comment by bobeff** [comment] 2019-08-13 19:01
> choosenim read's nimble's config. It seems like you've got stuff in there that's not supported by this version of choosenim.

@dom96 If so, how is it working when I built it locally?

**Comment by dom96** [comment] 2019-08-13 19:26
I assume you've built choosenim? It's because it was built with the Nimble version that you have installed, which probably has different config reading logic (choosenim imports code from Nimble for config reading).

**Comment by genotrance** [comment] 2020-01-11 04:45
Duplicate of https://github.com/dom96/choosenim/issues/109.

**Closed** 2020-01-12 17:21 UTC
