### ISSUE TITLE
github action failing on Windows when using choosenim

### ISSUE THREAD

**Issue by kdheepak** [dom96/choosenim#204] opened 2020-06-05 23:21 UTC
I'm getting the following error on github actions:

```
> Run jiro4989/setup-nim-action@v1
choosenim-init: Downloading choosenim-0.6.0_windows_amd64.zip
Archive:  /tmp/choosenim-0.6.0_windows_amd64.zip
  inflating: /tmp/choosenim/choosenim.exe  
  inflating: /tmp/choosenim/libeay64.dll  
  inflating: /tmp/choosenim/ssleay64.dll  
  inflating: /tmp/choosenim/runme.bat  
Downloading DLLs (openssl, pcre, ...)

[                                                  ] 0.06047% 4kb/s
[##################################################] 100.0% 0kb/s
 Extracting dlls.zip
Downloading Nim 1.2.0 from nim-lang.org

[                                                  ] 0.01945% 4kb/s
[##################################################] 100.0% 0kb/s
 Extracting nim-1.2.0_x64.zip
   Building Nim 1.2.0
  Compiler: Already built
     Tools: Already built
  Installed component 'nim'
  Installed component 'nimble'
  Installed component 'nimgrep'
  Installed component 'nimpretty'
  Installed component 'nimsuggest'
  Installed component 'testament'
      Hint: Use 'choosenim <version/channel> --firstInstall' to add
        ... C:\Users\runneradmin\.nimble\bin to your PATH.
   Switched to Nim 1.2.0
    Prompt: C:\Users\runneradmin\.nimble\bin is not in your PATH environment variable.
        ...             Should it be added permanently? -> [forced yes]
      Note: PATH changes will only take effect in new sessions.
choosenim-init: ChooseNim installed in C:\Users\runneradmin\.nimble\bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.

d:\a\_actions\jiro4989\setup-nim-action\v1\lib\installer.js:81
                    throw err;
                    ^

Error: Command failed: choosenim 1.2.0

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'choosenim 1.2.0'
}
##[error]Error: Command failed: choosenim 1.2.0
```

I'm not able to test this locally since I don't have a windows machine. The author of the action seems to think it is related to choosenim: https://github.com/jiro4989/setup-nim-action/issues/21

I see a bunch of other recent issues opened but I'm not sure if it covers what the fix should be. I'm cc-ing @jiro4989 so they can update `setup-nim-action` once we figure out what change must be made.

**Comment by jiro4989** [comment] 2020-06-05 23:25
My windows-pc occured this error.

Environments:

* OS: Windows 10

```bash
$ ~/.nimble/bin/choosenim -v
choosenim v0.6.0 (2020-03-06 18:45:17) [windows/amd64]

$ ~/.nimble/bin/choosenim.exe 1.2.0
      Info: C:\Users\jiro4989\.choosenim\downloads\dlls.zip already downloaded
 Extracting dlls.zip
     Error: Unable to extract. Error was '既に存在するファイルを作成することはできません。
        ... '.
```

**Comment by dom96** [comment] 2020-06-09 21:22
> '既に存在するファイルを作成することはできません。

Means you cannot create a file that already exists. This is being fixed in https://github.com/dom96/choosenim/pull/201.

This shouldn't happen unless you've modified the DLLs in ~/.nimble/bin though. Why would your GitHub action do that? Are you sure that it's experiencing the same error?

**Comment by jiro4989** [comment] 2020-06-10 00:50
> This shouldn't happen unless you've modified the DLLs in ~/.nimble/bin though. Why would your GitHub action do that? Are you sure that it's experiencing the same error?

No, I didn't modified DLLs.
This error message is a message that `choosenim` printed on my WindowsPC.
Steps are below.

```bash
# GitBash
curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
sh init.sh -y
choosenim 1.2.0 # error
```

This steps same steps of GitHub Actions.
But GitHub Actions didn't print `既に存在するファイルを作成することはできません。`
See report-log of @kdheepak.

I thought that Windows OS may be related to this eror, and reported it.
I’m sorry if I misled you.

**Comment by jiro4989** [comment] 2020-06-12 17:53
I did it.

```bash
$ cat install.sh
#!/bin/bash

set -eux

date

cd /tmp

rm -rf ~/.nimble/bin
rm -rf ~/.choosenim

curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
sh init.sh -y

nim -v
nimble -v
choosenim -v

choosenim 1.2.0

date
```

```bash
$ bash install.sh
+ date
2020年 6月 13日 土曜日 02:46:14
+ cd /tmp
+ rm -rf /c/Users/jiro4989/.nimble/bin
+ rm -rf /c/Users/jiro4989/.choosenim
+ curl https://nim-lang.org/choosenim/init.sh -sSf
+ sh init.sh -y
choosenim-init: Downloading choosenim-0.6.0_windows_amd64.zip
Archive:  /tmp/choosenim-0.6.0_windows_amd64.zip
  inflating: /tmp/choosenim/choosenim.exe
  inflating: /tmp/choosenim/libeay64.dll
  inflating: /tmp/choosenim/ssleay64.dll
  inflating: /tmp/choosenim/runme.bat
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: Forced Yes
Downloading C compiler (Mingw64)

[                                                  ] 0.005998% 4kb/s
[######                                            ] 13.81% 9208kb/s
[##################                                ] 37.64% 15888kb/s
[##############################                    ] 60.90% 15516kb/s
[##########################################        ] 84.88% 15992kb/s
[##################################################] 100.0% 0kb/s
 Extracting mingw64.7z
Downloading DLLs (openssl, pcre, ...)

[                                                  ] 0.06047% 4kb/s
[##################################################] 100.0% 0kb/s
 Extracting dlls.zip
Downloading Nim 1.2.0 from nim-lang.org

[                                                  ] 0.01945% 4kb/s
[##############                                    ] 29.84% 6132kb/s
[##################################################] 100.0% 0kb/s
 Extracting nim-1.2.0_x64.zip
   Building Nim 1.2.0
  Compiler: Already built
     Tools: Already built
  Installed component 'nim'
  Installed component 'nimble'
  Installed component 'nimgrep'
  Installed component 'nimpretty'
  Installed component 'nimsuggest'
  Installed component 'testament'
  Installed component 'gcc'
  Installed component 'g++'
  Installed component 'gdb'
  Installed component 'ld'
   Switched to Nim 1.2.0
choosenim-init: ChooseNim installed in C:\Users\jiro4989\.nimble\bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.
+ nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
+ nimble -v
nimble v0.11.0 compiled at 2020-04-03 12:44:31
git hash: 4007b2a778429a978e12307bf13a038029b4c4d9

+ choosenim -v
choosenim v0.6.0 (2020-03-06 18:45:17) [windows/amd64]
+ choosenim 1.2.0
      Info: C:\Users\jiro4989\.choosenim\downloads\dlls.zip already downloaded
 Extracting dlls.zip
     Error: Unable to extract. Error was '既に存在するファイルを作成することはできません。
        ... '.

```

**Comment by dom96** [comment] 2020-06-12 18:16
So it works fine on the first try. Then you try it again, choosenim doesn't find the DLLs in your PATH (because you haven't added `C:\Users\jiro4989\.nimble\bin` to your PATH) and so you end up reproducing https://github.com/dom96/choosenim/issues/199.

If that's what your GitHub actions script does then simply ensure the PATH is set correctly before running `choosenim 1.2.0`.

**Comment by dom96** [comment] 2020-10-01 21:21
Not sure we can do much here. The bug was fixed and should be available in a new release soon.

**Closed by dom96** 2020-10-01 21:21 UTC
