### ISSUE TITLE
i can't compile my program

### ISSUE THREAD

**Issue by tbutton2005** [dom96/choosenim#153] opened 2020-01-01 04:58 UTC
max@max-pc:~/Documents/something$ nim c something
     Error: Spawning of process failed. (Error was: Additional info: "Could not find command: \'/home/max/.choosenim/toolchains/nim-1.0.4/bin/nim\'. OS error: Permission denied")
      Info: If unexpected, please report this error to https://github.com/dom96/choosenim

**Comment by dom96** [comment] 2020-01-01 11:12
``chmod +x /home/max/.choosenim/toolchains/nim-1.0.4/bin/nim`` might help, but yeah this is a bug.

**Comment by tbutton2005** [comment] 2020-01-02 06:18
Thanks.

**Comment by dom96** [comment] 2020-01-02 21:23
I'll leave this open if you don't mind so we can fix the cause. Can you tell me your choosenim version?

**Comment by genotrance** [comment] 2020-01-10 16:52
@dom96 - Isn't this a duplicate of #147?

@tbutton2005 - It will be great if you could remove `~/.choosenim`, download choosenim manually from the releases page and run `./choosenim --debug 1.0.4` and provide the output.

**Comment by dom96** [comment] 2020-01-11 12:44
Yeah, seems it's a duplicate.

**Closed by dom96** 2020-01-11 12:44 UTC
