### ISSUE TITLE
1.4.4, broken install, wrong URL

### ISSUE THREAD

**Issue by juancarlospaco** [dom96/choosenim#249] opened 2021-02-24 08:33 UTC
```console
PS C:\Users\user> .\choosenim-0.7.4_windows_amd64.exe update self
   Updating choosenim
      Info: Already up to date at version 0.7.4

PS C:\Users\user> .\choosenim-0.7.4_windows_amd64.exe --yes --verbose --noColor --debug --firstInstall stable

     Debug: Reporting to analytics...
       Http Requesting http://nim-lang.org/channels/stable
Downloading Nim 1.4.4 from nim-lang.org
       GET: http://nim-lang.org/download/nim-1.4.4_x8.zip
[#                                                 ] 0mb 0kb/s

      Info: Couldn't download file from http://nim-lang.org/download/nim-1.4.4_x8.zip.

        ... Response was: 404 Not Found
     Debug: Reporting to analytics...
      Info: Binary build unavailable, building from source

       GET: http://nim-lang.org/download/nim-1.4.4.tar.xz

[##################################################] 100.0% 0kb/s
     Debug: Reporting to analytics...
 Extracting nim-1.4.4.tar.xz
     Debug: Reporting to analytics...
   Building Nim 1.4.4
   Building koch
  Executing bin/nim.exe c koch
   Cleaning failed build
   Warning: Cleaning failed: The process cannot access the file because it is being used by another process.
        ... Additional info: "C:\\Users\\user\\.choosenim\\toolchains\\nim-1.4.4"
     Debug: Reporting to analytics...
     Debug: Reporting to analytics...
oserr.nim(94)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
Additional info: "Requested command not found: \'bin/nim.exe c koch\'. OS error:" [OSError]

PS C:\Users\user>
```

- It tries to download from http://nim-lang.org/download/nim-1.4.4_x8.zip  Notice the `x8.zip` ?.
- But theres binary for Windows at https://nim-lang.org/download/nim-1.4.4_x64.zip
- The `"C:\\Users\\user\\.choosenim\"` is all empty folders.
- It says `Reporting to analytics...` like 6 ~ 8 times ?.
- With just the `--firstInstall` option is the same.
- Running on `cmd.exe` is the same.

**Comment by dom96** [comment] 2021-02-24 20:49
Weird that it failed the build.

But that's a separate issue. The first issue is that it gets the nightly filename incorrectly, the code for that is here: https://github.com/dom96/choosenim/blob/master/src/choosenimpkg/download.nim#L272

So this code must be broken: https://github.com/dom96/choosenim/blob/master/src/choosenimpkg/utils.nim#L91

**Comment by juancarlospaco** [comment] 2021-02-25 15:30
If you think is too uncommon bug, then close it. I git cloned anyway.
I just think that maybe the generated URL should have a test.

**Comment by timotheecour** [comment] 2021-02-25 18:40
> If you think is too uncommon bug, then close it

isn't it likely to affect other users?

**Comment by dom96** [comment] 2021-02-25 23:28
I don't think it's uncommon, but I would appreciate your help in diagnosing the cause and maybe even coming up with a PR to fix it :)

**Comment by dom96** [comment] 2022-10-22 22:49
This should be fixed now.

**Closed by dom96** 2022-10-22 22:49 UTC
