### ISSUE TITLE
Invalid argument OSError on practically every command

### ISSUE THREAD

**Issue by squattingmonk** [dom96/choosenim#240] opened 2020-10-22 17:24 UTC
Installing 0.7.4 on Arch Linux using either the prebuilt binary or the curl method yields an `OSError` on practically every command:

Using curl:
```
$ curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
$ sh init.sh -y
choosenim-init: Downloading choosenim-0.7.4_linux_amd64
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]

$ export CHOOSENIM_CHOOSE_VERSION=1.4.0
$ sh init.sh -y
choosenim-init: Downloading choosenim-0.7.4_linux_amd64
Downloading Nim 1.4.0 from nim-lang.org
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument

$ export CHOOSENIM_CHOOSE_VERSION=1.0.8
$ sh init.sh -y
choosenim-init: Downloading choosenim-0.7.4_linux_amd64
Downloading Nim 1.0.8 from nim-lang.org
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]
```
Using binary:
```
$ choosenim 1.4.0
choosenim 1.4.0
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
y
    Answer: Downloading Nim 1.4.0 from nim-lang.org
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]

$ choosenim 1.0.8
Downloading Nim 1.0.8 from nim-lang.org
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]

$ choosenim update stable
   Updating stable
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]

$ choosenim versions
oserr.nim(94)            raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]
```

The only arguments that appear to work when passed to the binary are `--help` and `--version`.

I've also tried installing choosenim with nimble, but it fails to build (#239).

## Details
OS: Arch Linux 5.9.1
Nim: 1.4.0
Nimble: 0.11.0

**Comment by genotrance** [comment] 2020-10-22 21:12
I just tried this on the latest Arch Linux [docker](https://hub.docker.com/_/archlinux?tab=tags) image and it worked fine for me. Can you try the [debug build](https://github.com/dom96/choosenim/releases/tag/v0.7.4) of choosenim and see what you get?

**Comment by squattingmonk** [comment] 2020-10-24 22:40
Here's with the debug build:
```
$ ./choosenim-0.7.4_linux_amd64_debug update stable

    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
y
    Answer:    Updating stable
/home/travis/build/dom96/choosenim/src/choosenim.nim(331) choosenim
/home/travis/build/dom96/choosenim/src/choosenim.nim(304) performAction
/home/travis/build/dom96/choosenim/src/choosenim.nim(159) update
/home/travis/build/dom96/choosenim/src/choosenimpkg/channel.nim(37) getChannelVersion
/home/travis/build/dom96/choosenim/src/choosenimpkg/download.nim(373) retrieveUrl
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/httpclient.nim(1080) getContent
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/httpclient.nim(1075) get
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/httpclient.nim(1051) request
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/httpclient.nim(1027) request
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/httpclient.nim(977) requestAux
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/httpclient.nim(864) newConnection
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/net.nim(1657) dial
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/nativesockets.nim(266) getAddrInfo
/home/travis/.choosenim/toolchains/nim-1.2.6/lib/pure/includes/oserr.nim(94) raiseOSError
Error: unhandled exception: Invalid argument
Additional info: "Try again" [OSError]
```

**Comment by dom96** [comment] 2020-10-25 10:11
Fun, can you check if choosenim 0.6.0 works for you? Guessing this is caused by static-musl libc?

**Comment by squattingmonk** [comment] 2020-10-25 21:59
0.6.0 hangs indefinitely when attempting to download anything. The `versions` command works as expected, though.

**Comment by foisonocean** [comment] 2020-12-22 11:51
Same error for me with Arch Linux, is there any updates?

**Comment by dom96** [comment] 2020-12-28 11:53
We need help from someone that can repro this, can you try installing Nim manually (via pacman or otherwise) and seeing if you can use ``httpclient`` to retrieve a URL via `getContent`? (1.2.6 if you can since that appears to be the version that choosenim is built with right now)

**Comment by foisonocean** [comment] 2020-12-28 12:35
@dom96 I just download the version 1.4.2 from the pre-built binaries of nim-lang.org, and the `getContent` works fine for me.

**Comment by dom96** [comment] 2021-01-10 12:59
It looks like it's trying to `getAddrInfo` asynchronously and the OS is asking it to call it again because the DNS is not ready. It's possible this was resolved in 1.4. Can you reproduce it with 1.2.6? If so this will be resolved as soon as choosenim is built with 1.4.

**Comment by squattingmonk** [comment] 2021-01-10 20:36
`getContent` works for me on 1.2.6 as well.

Also, I've found that a nimble build of the latest tagged version works as expected. It works correctly on 1.2.6, 1.4.0, and 1.4.2. However, the binary release fails to work due to #248.

**Comment by dom96** [comment] 2022-07-06 14:29
This should be resolved by now. Feel free to reopen if not.

**Closed by dom96** 2022-07-06 14:29 UTC
Labels: Bug, High Priority, OS/Platform specific
