### ISSUE TITLE
Linux_arm not supported.

### ISSUE THREAD

**Issue by NopeDK** [dom96/choosenim#43] opened 2017-12-11 19:13 UTC
```
pi@raspberrypi:~ $ curl https://nim-lang.org/choosenim/init.sh -sSf | sh
choosenim-init: Error: Sorry, your platform (linux_arm) is not supported by choosenim.
```

**Comment by dom96** [comment] 2020-10-01 22:15
Closing as duplicate of #149.

**Closed by dom96** 2020-10-01 22:15 UTC
Labels: Feature
