### ISSUE TITLE
Linux version should be static linked

### ISSUE THREAD

**Issue by euantorano** [dom96/choosenim#76] opened 2018-08-08 13:51 UTC
The current Linux release is dynamically linked, which emans it doesn't seem to run on Alpine Linux. It would be sueful if the Linux downlaods were a single static binary that could be deployed anywhere without depending on `libc` and such.

**Comment by dom96** [comment] 2020-10-01 22:46
Duplicate of #216.

**Closed by dom96** 2020-10-01 22:46 UTC
