### ISSUE TITLE
GLIBC_2.27 not found

### ISSUE THREAD

**Issue by telatin** [dom96/choosenim#289] opened 2021-11-23 11:07 UTC
Hi, I report this problem found in the "compilation node" of an HPC Cluster (where basically you cant make any changes). I found some workarounds but since this installer is brilliant I hope in the future it might be able to support more platforms at the first attempt, thanks!

```
choosenim-init: Downloading choosenim-0.8.2_linux_amd64
/tmp/choosenim-0.8.2_linux_amd64: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/choosenim-0.8.2_linux_amd64)
```

(the node has glibc version: 2.17)

**Comment by dom96** [comment] 2021-11-23 11:40
Thanks for reporting, Definitely will look into a solution. Duplicate of #280.

**Closed by dom96** 2021-11-23 11:40 UTC
