### ISSUE TITLE
Init can't download choosenim

### ISSUE THREAD

**Issue by cuyler** [dom96/choosenim#139] opened 2019-09-25 15:14 UTC
after downloading/curl init.sh:

choosenim-init: Downloading choosenim-0.4.0_macosx_amd64
SIGBUS: Illegal storage access. (Attempt to read from nil?)

MacOS Version: 10.14.6

**Comment by treeform** [comment] 2019-09-25 22:01
I am on MacOS Version: 10.14.6

Everything worked fine and installed on my system:

```
curl https://nim-lang.org/choosenim/init.sh -sSf | sh
choosenim-init: Downloading choosenim-0.4.0_macosx_amd64
    Prompt: Can choosenim record and send anonymised telemetry data? [y/n]
        ... Anonymous aggregate user analytics allow us to prioritise
        ... fixes and features based on how, where and when people use Nim.
        ... For more details see: https://goo.gl/NzUEPf.
    Answer: Forced Yes
Downloading Nim 1.0.0 from nim-lang.org
[##################################################] 100.0% 0kb/s
 Extracting nim-1.0.0.tar.gz
   Building Nim 1.0.0
   Building tools (nimble, nimgrep, nimpretty, nimsuggest)
   Switched to Nim 1.0.0
choosenim-init: ChooseNim installed in /Users/andre.vonhouck/.nimble/bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.
choosenim-init: Place the following line in the ~/.profile or ~/.bashrc file.
choosenim-init:     export PATH=/Users/andre.vonhouck/.nimble/bin:$PATH
```

```
nim
Nim Compiler Version 1.0.0 [MacOSX: amd64]
Compiled at 2019-09-23
Copyright (c) 2006-2019 by Andreas Rumpf
```

What is your clang version?
```
clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by cuyler** [comment] 2019-09-25 22:14
```
clang -v
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I also tried llvm 7 ( clang too ) with no joy.

**Comment by genotrance** [comment] 2020-01-10 23:20
Instead of using init.sh, can you try downloading the latest choosenim release and running `choosenim --debug 1.0.4`? It will hopefully provide more details on the failure.

**Comment by genotrance** [comment] 2020-02-13 03:21
This is a duplicate of #122, can be closed.

**Closed by genotrance** 2020-02-13 03:21 UTC
